// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFirebaseUser = `-- name: CreateFirebaseUser :one
INSERT INTO users (name, email, firebase_uid)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateFirebaseUserParams struct {
	Name        string
	Email       pgtype.Text
	FirebaseUid pgtype.Text
}

func (q *Queries) CreateFirebaseUser(ctx context.Context, arg CreateFirebaseUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createFirebaseUser, arg.Name, arg.Email, arg.FirebaseUid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions s USING users u
WHERE s.user_id = u.id AND u.id = $1 AND u.family_id = $2
`

type DeleteUserSessionsParams struct {
	ID       int64
	FamilyID pgtype.Int8
}

func (q *Queries) DeleteUserSessions(ctx context.Context, arg DeleteUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, arg.ID, arg.FamilyID)
	return err
}

const firebaseUser = `-- name: FirebaseUser :one
SELECT u.id, u.name, u.email, u.firebase_uid, u.email_verified_at,
       COALESCE(u.family_id, 0) AS family_id, COALESCE(f.name, '') AS family_name,
       CASE WHEN u.id = (SELECT min(id) FROM users WHERE family_id = u.family_id)
            THEN true ELSE false END AS kepala,
       u.disabled_at
FROM users u LEFT JOIN families f ON f.id = u.family_id
WHERE u.firebase_uid = $1
`

type FirebaseUserRow struct {
	ID              int64
	Name            string
	Email           pgtype.Text
	FirebaseUid     pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	FamilyID        int64
	FamilyName      string
	Kepala          bool
	DisabledAt      pgtype.Timestamptz
}

func (q *Queries) FirebaseUser(ctx context.Context, firebaseUid pgtype.Text) (FirebaseUserRow, error) {
	row := q.db.QueryRow(ctx, firebaseUser, firebaseUid)
	var i FirebaseUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.FirebaseUid,
		&i.EmailVerifiedAt,
		&i.FamilyID,
		&i.FamilyName,
		&i.Kepala,
		&i.DisabledAt,
	)
	return i, err
}

const markFirebaseEmailVerified = `-- name: MarkFirebaseEmailVerified :exec
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, now())
WHERE firebase_uid = $1
`

func (q *Queries) MarkFirebaseEmailVerified(ctx context.Context, firebaseUid pgtype.Text) error {
	_, err := q.db.Exec(ctx, markFirebaseEmailVerified, firebaseUid)
	return err
}

const purgeSessions = `-- name: PurgeSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) PurgeSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeSessions)
	return err
}

const sessionUser = `-- name: SessionUser :one
SELECT u.id, u.name, u.email, u.firebase_uid, u.email_verified_at,
       COALESCE(u.family_id, 0) AS family_id, COALESCE(f.name, '') AS family_name,
       CASE WHEN u.id = (SELECT min(id) FROM users WHERE family_id = u.family_id)
            THEN true ELSE false END AS kepala
FROM sessions s
JOIN users u ON u.id = s.user_id
LEFT JOIN families f ON f.id = u.family_id
WHERE s.token = $1 AND s.expires_at > now() AND u.disabled_at IS NULL
  AND u.firebase_uid IS NOT NULL AND u.email_verified_at IS NOT NULL
`

type SessionUserRow struct {
	ID              int64
	Name            string
	Email           pgtype.Text
	FirebaseUid     pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	FamilyID        int64
	FamilyName      string
	Kepala          bool
}

func (q *Queries) SessionUser(ctx context.Context, token string) (SessionUserRow, error) {
	row := q.db.QueryRow(ctx, sessionUser, token)
	var i SessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.FirebaseUid,
		&i.EmailVerifiedAt,
		&i.FamilyID,
		&i.FamilyName,
		&i.Kepala,
	)
	return i, err
}
