// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const saveQuote = `-- name: SaveQuote :batchexec
INSERT INTO quotes (symbol, price_e4, currency, quoted_at, name, fetched_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (symbol) DO UPDATE SET
  price_e4 = EXCLUDED.price_e4, currency = EXCLUDED.currency,
  quoted_at = EXCLUDED.quoted_at, fetched_at = EXCLUDED.fetched_at,
  name = COALESCE(NULLIF(EXCLUDED.name, ''), quotes.name)
`

type SaveQuoteBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type SaveQuoteParams struct {
	Symbol   string
	PriceE4  int64
	Currency string
	QuotedAt pgtype.Timestamptz
	Name     string
}

func (q *Queries) SaveQuote(ctx context.Context, arg []SaveQuoteParams) *SaveQuoteBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Symbol,
			a.PriceE4,
			a.Currency,
			a.QuotedAt,
			a.Name,
		}
		batch.Queue(saveQuote, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &SaveQuoteBatchResults{br, len(arg), false}
}

func (b *SaveQuoteBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *SaveQuoteBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
