// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCategoryTransactions = `-- name: CountCategoryTransactions :one
SELECT count(*) FROM transactions
WHERE family_id = $1 AND kind = $2 AND category = $3
`

type CountCategoryTransactionsParams struct {
	FamilyID int64
	Kind     string
	Category pgtype.Text
}

func (q *Queries) CountCategoryTransactions(ctx context.Context, arg CountCategoryTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryTransactions, arg.FamilyID, arg.Kind, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1 AND family_id = $2
`

type DeleteCategoryParams struct {
	ID       int64
	FamilyID int64
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.FamilyID)
	return err
}

const ensureCategory = `-- name: EnsureCategory :exec
INSERT INTO categories (family_id, kind, name) VALUES ($1, $2, $3)
ON CONFLICT (family_id, kind, name) DO NOTHING
`

type EnsureCategoryParams struct {
	FamilyID int64
	Kind     string
	Name     string
}

func (q *Queries) EnsureCategory(ctx context.Context, arg EnsureCategoryParams) error {
	_, err := q.db.Exec(ctx, ensureCategory, arg.FamilyID, arg.Kind, arg.Name)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT c.id, c.kind, c.name, COALESCE(p.jumlah, 0) AS usage, c.budget_minor
FROM categories c
LEFT JOIN (
    SELECT t.kind, t.category, count(*) AS jumlah
    FROM transactions t
    WHERE t.family_id = $1
    GROUP BY t.kind, t.category
) p ON p.kind = c.kind AND p.category = c.name
WHERE c.family_id = $1 AND ($2::text = '' OR c.kind = $2)
ORDER BY c.kind, c.name
`

type GetCategoriesParams struct {
	FamilyID int64
	Kind     string
}

type GetCategoriesRow struct {
	ID          int64
	Kind        string
	Name        string
	Usage       int64
	BudgetMinor int64
}

func (q *Queries) GetCategories(ctx context.Context, arg GetCategoriesParams) ([]GetCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getCategories, arg.FamilyID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoriesRow
	for rows.Next() {
		var i GetCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Usage,
			&i.BudgetMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, kind, name FROM categories WHERE id = $1 AND family_id = $2
`

type GetCategoryParams struct {
	ID       int64
	FamilyID int64
}

type GetCategoryRow struct {
	ID   int64
	Kind string
	Name string
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.FamilyID)
	var i GetCategoryRow
	err := row.Scan(&i.ID, &i.Kind, &i.Name)
	return i, err
}

const getCategorySpending = `-- name: GetCategorySpending :many
SELECT t.kind, t.category, w.currency, SUM(t.amount_minor)::bigint AS minor
FROM transactions t
JOIN wallets w ON w.id = t.wallet_id
WHERE t.family_id = $1 AND t.kind IN ('expense', 'income')
  AND t.occurred_on >= $2::date AND t.occurred_on < $3::date
  AND t.occurred_on <= $4::date AND NOT t.is_adjustment
GROUP BY t.kind, t.category, w.currency
`

type GetCategorySpendingParams struct {
	FamilyID int64
	FromDate pgtype.Date
	ToDate   pgtype.Date
	Today    pgtype.Date
}

type GetCategorySpendingRow struct {
	Kind     string
	Category pgtype.Text
	Currency string
	Minor    int64
}

func (q *Queries) GetCategorySpending(ctx context.Context, arg GetCategorySpendingParams) ([]GetCategorySpendingRow, error) {
	rows, err := q.db.Query(ctx, getCategorySpending,
		arg.FamilyID,
		arg.FromDate,
		arg.ToDate,
		arg.Today,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategorySpendingRow
	for rows.Next() {
		var i GetCategorySpendingRow
		if err := rows.Scan(
			&i.Kind,
			&i.Category,
			&i.Currency,
			&i.Minor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransferRates = `-- name: GetTransferRates :many
SELECT DISTINCT ON (w.currency, w2.currency)
       w.currency AS from_currency, w2.currency AS to_currency,
       (t.amount_minor - t.admin_fee_minor)::bigint AS from_minor, t.amount_in_minor AS to_minor
FROM transactions t
JOIN wallets w ON w.id = t.wallet_id
JOIN wallets w2 ON w2.id = t.to_wallet_id
WHERE t.family_id = $1 AND t.kind = 'transfer' AND w.currency <> w2.currency
  AND t.amount_minor > t.admin_fee_minor
ORDER BY w.currency, w2.currency, t.occurred_on DESC, t.id DESC
`

type GetTransferRatesRow struct {
	FromCurrency string
	ToCurrency   string
	FromMinor    int64
	ToMinor      pgtype.Int8
}

func (q *Queries) GetTransferRates(ctx context.Context, familyID int64) ([]GetTransferRatesRow, error) {
	rows, err := q.db.Query(ctx, getTransferRates, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransferRatesRow
	for rows.Next() {
		var i GetTransferRatesRow
		if err := rows.Scan(
			&i.FromCurrency,
			&i.ToCurrency,
			&i.FromMinor,
			&i.ToMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCategory = `-- name: InsertCategory :exec
INSERT INTO categories (family_id, kind, name) VALUES ($1, $2, $3)
`

type InsertCategoryParams struct {
	FamilyID int64
	Kind     string
	Name     string
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) error {
	_, err := q.db.Exec(ctx, insertCategory, arg.FamilyID, arg.Kind, arg.Name)
	return err
}

const renameCategoryName = `-- name: RenameCategoryName :exec
UPDATE categories SET name = $1 WHERE id = $2 AND family_id = $3
`

type RenameCategoryNameParams struct {
	Name     string
	ID       int64
	FamilyID int64
}

func (q *Queries) RenameCategoryName(ctx context.Context, arg RenameCategoryNameParams) error {
	_, err := q.db.Exec(ctx, renameCategoryName, arg.Name, arg.ID, arg.FamilyID)
	return err
}

const renameTransactionCategory = `-- name: RenameTransactionCategory :exec
UPDATE transactions SET category = $1
WHERE family_id = $2 AND kind = $3
  AND category = $4
`

type RenameTransactionCategoryParams struct {
	NewName  pgtype.Text
	FamilyID int64
	Kind     string
	OldName  pgtype.Text
}

func (q *Queries) RenameTransactionCategory(ctx context.Context, arg RenameTransactionCategoryParams) error {
	_, err := q.db.Exec(ctx, renameTransactionCategory,
		arg.NewName,
		arg.FamilyID,
		arg.Kind,
		arg.OldName,
	)
	return err
}

const updateCategoryBudget = `-- name: UpdateCategoryBudget :execrows
UPDATE categories SET budget_minor = $1
WHERE family_id = $2 AND id = $3 AND kind = 'expense'
`

type UpdateCategoryBudgetParams struct {
	BudgetMinor int64
	FamilyID    int64
	ID          int64
}

func (q *Queries) UpdateCategoryBudget(ctx context.Context, arg UpdateCategoryBudgetParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCategoryBudget, arg.BudgetMinor, arg.FamilyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
