// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: families.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserFamily = `-- name: AssignUserFamily :exec
UPDATE users SET family_id = $1 WHERE id = $2
`

type AssignUserFamilyParams struct {
	FamilyID pgtype.Int8
	ID       int64
}

func (q *Queries) AssignUserFamily(ctx context.Context, arg AssignUserFamilyParams) error {
	_, err := q.db.Exec(ctx, assignUserFamily, arg.FamilyID, arg.ID)
	return err
}

const countFamilyUsers = `-- name: CountFamilyUsers :one
SELECT count(*) FROM users WHERE family_id = $1
`

func (q *Queries) CountFamilyUsers(ctx context.Context, familyID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, countFamilyUsers, familyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFamilyByCode = `-- name: GetFamilyByCode :one
SELECT id, name, signup_code FROM families WHERE signup_code = $1
`

type GetFamilyByCodeRow struct {
	ID         int64
	Name       string
	SignupCode string
}

func (q *Queries) GetFamilyByCode(ctx context.Context, signupCode string) (GetFamilyByCodeRow, error) {
	row := q.db.QueryRow(ctx, getFamilyByCode, signupCode)
	var i GetFamilyByCodeRow
	err := row.Scan(&i.ID, &i.Name, &i.SignupCode)
	return i, err
}

const getFamilyByID = `-- name: GetFamilyByID :one
SELECT id, name, signup_code, signup_code_expires_at FROM families WHERE id = $1
`

type GetFamilyByIDRow struct {
	ID                  int64
	Name                string
	SignupCode          string
	SignupCodeExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetFamilyByID(ctx context.Context, id int64) (GetFamilyByIDRow, error) {
	row := q.db.QueryRow(ctx, getFamilyByID, id)
	var i GetFamilyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SignupCode,
		&i.SignupCodeExpiresAt,
	)
	return i, err
}

const getFamilyDetail = `-- name: GetFamilyDetail :one
SELECT id, name, signup_code, signup_code_expires_at, created_at
FROM families WHERE id = $1
`

type GetFamilyDetailRow struct {
	ID                  int64
	Name                string
	SignupCode          string
	SignupCodeExpiresAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) GetFamilyDetail(ctx context.Context, id int64) (GetFamilyDetailRow, error) {
	row := q.db.QueryRow(ctx, getFamilyDetail, id)
	var i GetFamilyDetailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SignupCode,
		&i.SignupCodeExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMembers = `-- name: GetMembers :many
SELECT u.id, u.name, u.created_at, u.disabled_at,
       CASE WHEN u.id = (SELECT min(id) FROM users WHERE family_id = u.family_id)
            THEN true ELSE false END AS kepala,
       (SELECT count(*) FROM transactions t
        WHERE t.family_id = u.family_id AND t.created_by = u.id) AS tx_count
FROM users u WHERE u.family_id = $1 ORDER BY u.id
`

type GetMembersRow struct {
	ID         int64
	Name       string
	CreatedAt  pgtype.Timestamptz
	DisabledAt pgtype.Timestamptz
	Kepala     bool
	TxCount    int64
}

func (q *Queries) GetMembers(ctx context.Context, familyID pgtype.Int8) ([]GetMembersRow, error) {
	rows, err := q.db.Query(ctx, getMembers, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersRow
	for rows.Next() {
		var i GetMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.Kepala,
			&i.TxCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFamily = `-- name: InsertFamily :one
INSERT INTO families (name, signup_code, billing_owner_user_id)
VALUES ($1, $2, $3)
RETURNING id, name, signup_code, signup_code_expires_at, created_at
`

type InsertFamilyParams struct {
	Name               string
	SignupCode         string
	BillingOwnerUserID pgtype.Int8
}

type InsertFamilyRow struct {
	ID                  int64
	Name                string
	SignupCode          string
	SignupCodeExpiresAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) InsertFamily(ctx context.Context, arg InsertFamilyParams) (InsertFamilyRow, error) {
	row := q.db.QueryRow(ctx, insertFamily, arg.Name, arg.SignupCode, arg.BillingOwnerUserID)
	var i InsertFamilyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SignupCode,
		&i.SignupCodeExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkUserToFamily = `-- name: LinkUserToFamily :execrows
UPDATE users SET family_id = $1, name = $3
WHERE id = $2 AND family_id IS NULL
`

type LinkUserToFamilyParams struct {
	FamilyID pgtype.Int8
	ID       int64
	Name     string
}

func (q *Queries) LinkUserToFamily(ctx context.Context, arg LinkUserToFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkUserToFamily, arg.FamilyID, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFamilies = `-- name: ListFamilies :many
SELECT f.id, f.name, f.signup_code, f.signup_code_expires_at, f.created_at,
       (SELECT count(*) FROM users u WHERE u.family_id = f.id) AS members,
       (SELECT count(*) FROM wallets w WHERE w.family_id = f.id) AS wallets,
       (SELECT count(*) FROM transactions t WHERE t.family_id = f.id) AS txs
FROM families f ORDER BY f.id
`

type ListFamiliesRow struct {
	ID                  int64
	Name                string
	SignupCode          string
	SignupCodeExpiresAt pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	Members             int64
	Wallets             int64
	Txs                 int64
}

func (q *Queries) ListFamilies(ctx context.Context) ([]ListFamiliesRow, error) {
	rows, err := q.db.Query(ctx, listFamilies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFamiliesRow
	for rows.Next() {
		var i ListFamiliesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SignupCode,
			&i.SignupCodeExpiresAt,
			&i.CreatedAt,
			&i.Members,
			&i.Wallets,
			&i.Txs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFamilyByCode = `-- name: LockFamilyByCode :one
SELECT id FROM families
WHERE signup_code = $1 AND signup_code_expires_at > now() FOR UPDATE
`

func (q *Queries) LockFamilyByCode(ctx context.Context, signupCode string) (int64, error) {
	row := q.db.QueryRow(ctx, lockFamilyByCode, signupCode)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const seedFamilyCategories = `-- name: SeedFamilyCategories :exec
INSERT INTO categories (family_id, kind, name)
SELECT $1::bigint, 'expense', name
FROM unnest(ARRAY['Belanja', 'Tagihan', 'Transportasi', 'Makanan', 'Kesehatan', 'Lainnya']) AS name
UNION ALL
SELECT $1::bigint, 'income', name
FROM unnest(ARRAY['Gaji', 'Bonus', 'Hadiah', 'Investasi', 'Lainnya']) AS name
`

func (q *Queries) SeedFamilyCategories(ctx context.Context, dollar_1 int64) error {
	_, err := q.db.Exec(ctx, seedFamilyCategories, dollar_1)
	return err
}

const setMemberActive = `-- name: SetMemberActive :execrows
UPDATE users u SET disabled_at = $1
WHERE u.id = $2 AND u.family_id = $3
  AND NOT (u.id = (SELECT min(id) FROM users WHERE family_id = u.family_id))
`

type SetMemberActiveParams struct {
	DisabledAt pgtype.Timestamptz
	ID         int64
	FamilyID   pgtype.Int8
}

func (q *Queries) SetMemberActive(ctx context.Context, arg SetMemberActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMemberActive, arg.DisabledAt, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFamily = `-- name: UpdateFamily :execrows
UPDATE families SET name = COALESCE(NULLIF($1::text, ''), name),
       signup_code = COALESCE(NULLIF($2::text, ''), signup_code),
       signup_code_expires_at = CASE WHEN $2::text = '' THEN signup_code_expires_at ELSE now() + interval '7 days' END
WHERE id = $3
`

type UpdateFamilyParams struct {
	Name string
	Code string
	ID   int64
}

func (q *Queries) UpdateFamily(ctx context.Context, arg UpdateFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateFamily, arg.Name, arg.Code, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userLinkedForUpdate = `-- name: UserLinkedForUpdate :one
SELECT CASE WHEN family_id IS NOT NULL THEN true ELSE false END AS linked
FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) UserLinkedForUpdate(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, userLinkedForUpdate, id)
	var linked bool
	err := row.Scan(&linked)
	return linked, err
}
