// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: investments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLaterInvestmentSales = `-- name: CountLaterInvestmentSales :one
SELECT count(*) FROM transactions
WHERE family_id = $1 AND investment_id = $2 AND kind = 'invest_sell' AND id > $3
`

type CountLaterInvestmentSalesParams struct {
	FamilyID     int64
	InvestmentID pgtype.Int8
	ID           int64
}

func (q *Queries) CountLaterInvestmentSales(ctx context.Context, arg CountLaterInvestmentSalesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLaterInvestmentSales, arg.FamilyID, arg.InvestmentID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments
  (family_id, kind, name, varian, symbol, currency, wallet_id,
   manual_price_e4, manual_price_on, note)
VALUES ($1, $2, $3, $4,
        $5, $6, NULLIF($7::bigint, 0),
        NULLIF($8::bigint, 0), $9::date,
        $10)
RETURNING id
`

type CreateInvestmentParams struct {
	FamilyID      int64
	Kind          string
	Name          string
	Varian        string
	Symbol        string
	Currency      string
	WalletID      int64
	ManualPriceE4 int64
	ManualPriceOn pgtype.Date
	Note          string
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.FamilyID,
		arg.Kind,
		arg.Name,
		arg.Varian,
		arg.Symbol,
		arg.Currency,
		arg.WalletID,
		arg.ManualPriceE4,
		arg.ManualPriceOn,
		arg.Note,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteInvestment = `-- name: DeleteInvestment :execrows
DELETE FROM investments i
WHERE i.family_id = $1 AND i.id = $2
  AND NOT EXISTS (SELECT 1 FROM transactions t WHERE t.investment_id = i.id)
`

type DeleteInvestmentParams struct {
	FamilyID int64
	ID       int64
}

func (q *Queries) DeleteInvestment(ctx context.Context, arg DeleteInvestmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvestment, arg.FamilyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteInvestmentTrade = `-- name: DeleteInvestmentTrade :execrows
DELETE FROM transactions
WHERE family_id = $1 AND investment_id = $2 AND id = $3
  AND kind IN ('invest_buy', 'invest_sell')
`

type DeleteInvestmentTradeParams struct {
	FamilyID     int64
	InvestmentID pgtype.Int8
	ID           int64
}

func (q *Queries) DeleteInvestmentTrade(ctx context.Context, arg DeleteInvestmentTradeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvestmentTrade, arg.FamilyID, arg.InvestmentID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvestments = `-- name: GetInvestments :many
SELECT i.id, i.kind, i.name, i.varian, i.symbol, i.currency,
       COALESCE(i.wallet_id, 0) AS wallet_id, COALESCE(w.name, '') AS wallet_name,
       COALESCE(i.manual_price_e4, 0) AS manual_price_e4, i.manual_price_on,
       i.note, i.created_at,
       COALESCE((SELECT SUM(CASE WHEN t.kind = 'invest_buy' THEN t.qty_e8 ELSE -t.qty_e8 END)
                 FROM transactions t WHERE t.investment_id = i.id), 0)::bigint AS qty_e8,
       COALESCE((SELECT SUM(CASE WHEN t.kind = 'invest_buy' THEN t.amount_minor ELSE -t.cost_basis_minor END)
                 FROM transactions t WHERE t.investment_id = i.id), 0)::bigint AS modal_minor,
       COALESCE((SELECT SUM(t.admin_fee_minor) FROM transactions t
                 WHERE t.investment_id = i.id AND t.kind = 'invest_buy'), 0)::bigint AS fee_minor,
       (SELECT count(*) FROM transactions t WHERE t.investment_id = i.id AND t.kind = 'invest_buy') AS lots,
       (SELECT t.occurred_on FROM transactions t
        WHERE t.investment_id = i.id AND t.kind = 'invest_buy'
        ORDER BY t.occurred_on DESC LIMIT 1) AS last_buy,
       (SELECT count(*) FROM transactions t WHERE t.investment_id = i.id AND t.kind = 'invest_sell') AS sales,
       COALESCE((SELECT SUM(t.amount_minor - t.cost_basis_minor) FROM transactions t
                 WHERE t.investment_id = i.id AND t.kind = 'invest_sell'), 0)::bigint AS realized_minor
FROM investments i
LEFT JOIN wallets w ON w.id = i.wallet_id
WHERE i.family_id = $1
  AND ($2::bigint = 0 OR i.id = $2)
ORDER BY CASE i.kind WHEN 'gold' THEN 1 WHEN 'stock' THEN 2 ELSE 3 END, i.name, i.varian
`

type GetInvestmentsParams struct {
	FamilyID     int64
	InvestmentID int64
}

type GetInvestmentsRow struct {
	ID            int64
	Kind          string
	Name          string
	Varian        string
	Symbol        string
	Currency      string
	WalletID      int64
	WalletName    string
	ManualPriceE4 int64
	ManualPriceOn pgtype.Date
	Note          string
	CreatedAt     pgtype.Timestamptz
	QtyE8         int64
	ModalMinor    int64
	FeeMinor      int64
	Lots          int64
	LastBuy       pgtype.Date
	Sales         int64
	RealizedMinor int64
}

func (q *Queries) GetInvestments(ctx context.Context, arg GetInvestmentsParams) ([]GetInvestmentsRow, error) {
	rows, err := q.db.Query(ctx, getInvestments, arg.FamilyID, arg.InvestmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInvestmentsRow
	for rows.Next() {
		var i GetInvestmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.Varian,
			&i.Symbol,
			&i.Currency,
			&i.WalletID,
			&i.WalletName,
			&i.ManualPriceE4,
			&i.ManualPriceOn,
			&i.Note,
			&i.CreatedAt,
			&i.QtyE8,
			&i.ModalMinor,
			&i.FeeMinor,
			&i.Lots,
			&i.LastBuy,
			&i.Sales,
			&i.RealizedMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const investmentTradePosition = `-- name: InvestmentTradePosition :one
SELECT COALESCE(SUM(CASE WHEN t.kind = 'invest_buy' THEN t.qty_e8 ELSE -t.qty_e8 END), 0)::bigint AS qty_e8,
       COALESCE(SUM(CASE WHEN t.kind = 'invest_buy' THEN t.amount_minor ELSE -t.cost_basis_minor END), 0)::bigint AS cost_minor,
       (SELECT latest.occurred_on FROM transactions latest
        WHERE latest.family_id = $1 AND latest.investment_id = $2
        ORDER BY latest.occurred_on DESC LIMIT 1) AS last_trade
FROM transactions t WHERE t.family_id = $1 AND t.investment_id = $2
`

type InvestmentTradePositionParams struct {
	FamilyID     int64
	InvestmentID pgtype.Int8
}

type InvestmentTradePositionRow struct {
	QtyE8     int64
	CostMinor int64
	LastTrade pgtype.Date
}

func (q *Queries) InvestmentTradePosition(ctx context.Context, arg InvestmentTradePositionParams) (InvestmentTradePositionRow, error) {
	row := q.db.QueryRow(ctx, investmentTradePosition, arg.FamilyID, arg.InvestmentID)
	var i InvestmentTradePositionRow
	err := row.Scan(&i.QtyE8, &i.CostMinor, &i.LastTrade)
	return i, err
}

const lastInvestmentSaleDate = `-- name: LastInvestmentSaleDate :one
SELECT occurred_on FROM transactions
WHERE family_id = $1 AND investment_id = $2 AND kind = 'invest_sell'
ORDER BY occurred_on DESC LIMIT 1
`

type LastInvestmentSaleDateParams struct {
	FamilyID     int64
	InvestmentID pgtype.Int8
}

func (q *Queries) LastInvestmentSaleDate(ctx context.Context, arg LastInvestmentSaleDateParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, lastInvestmentSaleDate, arg.FamilyID, arg.InvestmentID)
	var occurred_on pgtype.Date
	err := row.Scan(&occurred_on)
	return occurred_on, err
}

const lockInvestment = `-- name: LockInvestment :one
SELECT id FROM investments WHERE family_id = $1 AND id = $2 FOR UPDATE
`

type LockInvestmentParams struct {
	FamilyID int64
	ID       int64
}

func (q *Queries) LockInvestment(ctx context.Context, arg LockInvestmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockInvestment, arg.FamilyID, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateInvestment = `-- name: UpdateInvestment :execrows
UPDATE investments SET name = $1, varian = $2,
       symbol = $3, currency = $4,
       wallet_id = NULLIF($5::bigint, 0),
       manual_price_e4 = NULLIF($6::bigint, 0),
       manual_price_on = $7::date, note = $8
WHERE family_id = $9 AND id = $10
`

type UpdateInvestmentParams struct {
	Name          string
	Varian        string
	Symbol        string
	Currency      string
	WalletID      int64
	ManualPriceE4 int64
	ManualPriceOn pgtype.Date
	Note          string
	FamilyID      int64
	ID            int64
}

func (q *Queries) UpdateInvestment(ctx context.Context, arg UpdateInvestmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateInvestment,
		arg.Name,
		arg.Varian,
		arg.Symbol,
		arg.Currency,
		arg.WalletID,
		arg.ManualPriceE4,
		arg.ManualPriceOn,
		arg.Note,
		arg.FamilyID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
