// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          int64
	Kind        string
	Name        string
	CreatedAt   pgtype.Timestamptz
	FamilyID    int64
	BudgetMinor int64
}

type Family struct {
	ID                  int64
	Name                string
	SignupCode          string
	CreatedAt           pgtype.Timestamptz
	SignupCodeExpiresAt pgtype.Timestamptz
	BillingOwnerUserID  pgtype.Int8
	BetaStartedAt       pgtype.Timestamptz
	BetaCohort          string
}

type Investment struct {
	ID            int64
	FamilyID      int64
	Kind          string
	Name          string
	Varian        string
	Symbol        string
	Currency      string
	WalletID      pgtype.Int8
	ManualPriceE4 pgtype.Int8
	ManualPriceOn pgtype.Date
	Note          string
	CreatedAt     pgtype.Timestamptz
}

type Party struct {
	ID        int64
	FamilyID  int64
	Name      string
	Note      string
	CreatedAt pgtype.Timestamptz
}

type Quote struct {
	Symbol    string
	PriceE4   int64
	Currency  string
	QuotedAt  pgtype.Timestamptz
	Name      string
	FetchedAt pgtype.Timestamptz
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

type Transaction struct {
	ID             int64
	Kind           string
	OccurredOn     pgtype.Date
	WalletID       pgtype.Int8
	AmountMinor    int64
	Category       pgtype.Text
	ToWalletID     pgtype.Int8
	AmountInMinor  pgtype.Int8
	AdminFeeMinor  int64
	Note           string
	CreatedBy      pgtype.Int8
	CreatedAt      pgtype.Timestamptz
	FamilyID       int64
	PartyID        pgtype.Int8
	Currency       pgtype.Text
	InvestmentID   pgtype.Int8
	QtyE8          pgtype.Int8
	SeriesID       pgtype.Int8
	SeriesSeq      pgtype.Int2
	SeriesN        pgtype.Int2
	SeriesKind     pgtype.Text
	CostBasisMinor pgtype.Int8
	IsAdjustment   bool
}

type User struct {
	ID              int64
	Name            string
	PasswordHash    pgtype.Text
	CreatedAt       pgtype.Timestamptz
	FamilyID        pgtype.Int8
	DisabledAt      pgtype.Timestamptz
	Username        pgtype.Text
	Email           pgtype.Text
	FirebaseUid     pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

type Wallet struct {
	ID                  int64
	Name                string
	Type                string
	Provider            pgtype.Text
	Currency            string
	InitialBalanceMinor int64
	CreatedAt           pgtype.Timestamptz
	FamilyID            int64
	SettlementDay       pgtype.Int2
	PaymentDay          pgtype.Int2
	CreditLimitMinor    pgtype.Int8
}
