// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          int64
	Kind        string
	Name        string
	CreatedAt   pgtype.Timestamptz
	FamilyID    int64
	BudgetMinor int64
}

type Family struct {
	ID                  int64
	Name                string
	SignupCode          string
	CreatedAt           pgtype.Timestamptz
	SignupCodeExpiresAt pgtype.Timestamptz
	BillingOwnerUserID  pgtype.Int8
	BetaStartedAt       pgtype.Timestamptz
	BetaCohort          string
	PeriodStartDay      int16
	LedgerRevision      int64
	SavingTarget        int16
}

type Investment struct {
	ID            int64
	FamilyID      int64
	Kind          string
	Name          string
	Varian        string
	Symbol        string
	Currency      string
	WalletID      pgtype.Int8
	ManualPriceE4 pgtype.Int8
	ManualPriceOn pgtype.Date
	Note          string
	CreatedAt     pgtype.Timestamptz
}

type Party struct {
	ID              int64
	FamilyID        int64
	Name            string
	Note            string
	CreatedAt       pgtype.Timestamptz
	DueOn           pgtype.Date
	PaymentWalletID pgtype.Int8
}

type Quote struct {
	Symbol    string
	PriceE4   int64
	Currency  string
	QuotedAt  pgtype.Timestamptz
	Name      string
	FetchedAt pgtype.Timestamptz
}

type SavingsGoal struct {
	FamilyID    int64
	Name        string
	TargetMinor int64
	TargetOn    pgtype.Date
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

type Subscription struct {
	ID             int64
	FamilyID       int64
	WalletID       int64
	Name           string
	Category       string
	AmountMinor    int64
	NextDate       pgtype.Date
	BillingDay     int16
	IntervalMonths int16
	Active         bool
}

type Transaction struct {
	ID             int64
	Kind           string
	OccurredOn     pgtype.Date
	WalletID       pgtype.Int8
	AmountMinor    int64
	Category       pgtype.Text
	ToWalletID     pgtype.Int8
	AmountInMinor  pgtype.Int8
	AdminFeeMinor  int64
	Note           string
	CreatedBy      pgtype.Int8
	CreatedAt      pgtype.Timestamptz
	FamilyID       int64
	PartyID        pgtype.Int8
	Currency       pgtype.Text
	InvestmentID   pgtype.Int8
	QtyE8          pgtype.Int8
	SeriesID       pgtype.Int8
	SeriesSeq      pgtype.Int2
	SeriesN        pgtype.Int2
	SeriesKind     pgtype.Text
	CostBasisMinor pgtype.Int8
	IsAdjustment   bool
	OccurredTime   string
	RecorderID     pgtype.Int8
	Receipt        []byte
	ReceiptMime    string
}

type TransactionReaction struct {
	TransactionID int64
	UserID        int64
}

type User struct {
	ID              int64
	Name            string
	PasswordHash    pgtype.Text
	CreatedAt       pgtype.Timestamptz
	FamilyID        pgtype.Int8
	DisabledAt      pgtype.Timestamptz
	Username        pgtype.Text
	Email           pgtype.Text
	FirebaseUid     pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	Avatar          []byte
	AvatarMime      string
}

type Wallet struct {
	ID                  int64
	Name                string
	Type                string
	Provider            pgtype.Text
	Currency            string
	InitialBalanceMinor int64
	CreatedAt           pgtype.Timestamptz
	FamilyID            int64
	SettlementDay       pgtype.Int2
	PaymentDay          pgtype.Int2
	CreditLimitMinor    pgtype.Int8
	OwnerLabel          string
	LastFour            string
	Cardholder          string
	IsPrimary           bool
}
