// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parties.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPartyTransactions = `-- name: CountPartyTransactions :one
SELECT count(*) FROM transactions WHERE family_id = $1 AND party_id = $2
`

type CountPartyTransactionsParams struct {
	FamilyID int64
	PartyID  pgtype.Int8
}

func (q *Queries) CountPartyTransactions(ctx context.Context, arg CountPartyTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPartyTransactions, arg.FamilyID, arg.PartyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteParty = `-- name: DeleteParty :execrows
DELETE FROM parties WHERE id = $1 AND family_id = $2
`

type DeletePartyParams struct {
	ID       int64
	FamilyID int64
}

func (q *Queries) DeleteParty(ctx context.Context, arg DeletePartyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteParty, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCardBalances = `-- name: GetCardBalances :one
SELECT (
    (SELECT w.initial_balance_minor FROM wallets w
     WHERE w.id = $1 AND w.family_id = $2)
    + COALESCE((SELECT SUM(CASE WHEN t.kind IN ('income', 'debt_in', 'loan_in', 'invest_sell')
                                THEN t.amount_minor ELSE -t.amount_minor END)
                FROM transactions t
                WHERE t.family_id = $2 AND t.wallet_id = $1
                  AND t.occurred_on <= $3::date), 0)
    + COALESCE((SELECT SUM(t.amount_in_minor) FROM transactions t
                WHERE t.family_id = $2 AND t.to_wallet_id = $1
                  AND t.occurred_on <= $3::date), 0)
)::bigint AS at_settlement,
(
    COALESCE((SELECT SUM(t.amount_in_minor) FROM transactions t
              WHERE t.family_id = $2 AND t.to_wallet_id = $1
                AND t.occurred_on > $3::date
                AND t.occurred_on <= $4::date), 0)
    + COALESCE((SELECT SUM(t.amount_minor) FROM transactions t
                WHERE t.family_id = $2 AND t.wallet_id = $1
                  AND t.occurred_on > $3::date
                  AND t.occurred_on <= $4::date
                  AND t.kind IN ('income', 'debt_in', 'loan_in', 'invest_sell')), 0)
)::bigint AS credits_since
`

type GetCardBalancesParams struct {
	WalletID   int64
	FamilyID   int64
	Settlement pgtype.Date
	Today      pgtype.Date
}

type GetCardBalancesRow struct {
	AtSettlement int64
	CreditsSince int64
}

func (q *Queries) GetCardBalances(ctx context.Context, arg GetCardBalancesParams) (GetCardBalancesRow, error) {
	row := q.db.QueryRow(ctx, getCardBalances,
		arg.WalletID,
		arg.FamilyID,
		arg.Settlement,
		arg.Today,
	)
	var i GetCardBalancesRow
	err := row.Scan(&i.AtSettlement, &i.CreditsSince)
	return i, err
}

const getParties = `-- name: GetParties :many
SELECT p.id, p.name, p.note, COALESCE(b.cur, '') AS cur,
       COALESCE(b.hutang, 0)::bigint AS hutang,
       COALESCE(b.piutang, 0)::bigint AS piutang
FROM parties p
LEFT JOIN (
    SELECT t.party_id, COALESCE(w.currency, t.currency) AS cur,
           SUM(CASE t.kind WHEN 'debt_in' THEN t.amount_minor
                           WHEN 'debt_pay' THEN -t.amount_minor ELSE 0 END)::bigint AS hutang,
           SUM(CASE t.kind WHEN 'loan_out' THEN t.amount_minor
                           WHEN 'loan_in' THEN -t.amount_minor ELSE 0 END)::bigint AS piutang
    FROM transactions t
    LEFT JOIN wallets w ON w.id = t.wallet_id
    WHERE t.family_id = $1 AND t.party_id IS NOT NULL
    GROUP BY t.party_id, COALESCE(w.currency, t.currency)
) b ON b.party_id = p.id
WHERE p.family_id = $1
ORDER BY p.name, b.cur
`

type GetPartiesRow struct {
	ID      int64
	Name    string
	Note    string
	Cur     string
	Hutang  int64
	Piutang int64
}

func (q *Queries) GetParties(ctx context.Context, familyID int64) ([]GetPartiesRow, error) {
	rows, err := q.db.Query(ctx, getParties, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartiesRow
	for rows.Next() {
		var i GetPartiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Note,
			&i.Cur,
			&i.Hutang,
			&i.Piutang,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartyByName = `-- name: GetPartyByName :one
SELECT id, name, note FROM parties
WHERE family_id = $1 AND lower(name) = lower($2::text)
`

type GetPartyByNameParams struct {
	FamilyID int64
	Name     string
}

type GetPartyByNameRow struct {
	ID   int64
	Name string
	Note string
}

func (q *Queries) GetPartyByName(ctx context.Context, arg GetPartyByNameParams) (GetPartyByNameRow, error) {
	row := q.db.QueryRow(ctx, getPartyByName, arg.FamilyID, arg.Name)
	var i GetPartyByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.Note)
	return i, err
}

const insertParty = `-- name: InsertParty :one
INSERT INTO parties (family_id, name) VALUES ($1, $2) RETURNING id
`

type InsertPartyParams struct {
	FamilyID int64
	Name     string
}

func (q *Queries) InsertParty(ctx context.Context, arg InsertPartyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertParty, arg.FamilyID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateParty = `-- name: UpdateParty :execrows
UPDATE parties SET name = $1, note = $2 WHERE id = $3 AND family_id = $4
`

type UpdatePartyParams struct {
	Name     string
	Note     string
	ID       int64
	FamilyID int64
}

func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateParty,
		arg.Name,
		arg.Note,
		arg.ID,
		arg.FamilyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
