// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quotes.sql

package db

import (
	"context"
)

const getQuotes = `-- name: GetQuotes :many
SELECT symbol, price_e4, currency, quoted_at, name, fetched_at
FROM quotes
WHERE cardinality($1::text[]) = 0
   OR symbol = ANY($1::text[])
`

func (q *Queries) GetQuotes(ctx context.Context, symbols []string) ([]Quote, error) {
	rows, err := q.db.Query(ctx, getQuotes, symbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quote
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.Symbol,
			&i.PriceE4,
			&i.Currency,
			&i.QuotedAt,
			&i.Name,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsedSymbols = `-- name: GetUsedSymbols :many
SELECT DISTINCT symbol, kind FROM investments WHERE symbol <> ''
`

type GetUsedSymbolsRow struct {
	Symbol string
	Kind   string
}

func (q *Queries) GetUsedSymbols(ctx context.Context) ([]GetUsedSymbolsRow, error) {
	rows, err := q.db.Query(ctx, getUsedSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsedSymbolsRow
	for rows.Next() {
		var i GetUsedSymbolsRow
		if err := rows.Scan(&i.Symbol, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
