// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSubscription = `-- name: AdvanceSubscription :execrows
UPDATE subscriptions SET next_date = date_trunc('month', next_date + interval_months * INTERVAL '1 month')::date
    + LEAST(billing_day, EXTRACT(DAY FROM date_trunc('month', next_date + interval_months * INTERVAL '1 month') + INTERVAL '1 month - 1 day')::int) - 1
WHERE family_id=$1 AND id=$2 AND next_date=$3 AND active
`

type AdvanceSubscriptionParams struct {
	FamilyID int64
	ID       int64
	NextDate pgtype.Date
}

func (q *Queries) AdvanceSubscription(ctx context.Context, arg AdvanceSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceSubscription, arg.FamilyID, arg.ID, arg.NextDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSubscriptionCategories = `-- name: CountSubscriptionCategories :one
SELECT count(*) FROM subscriptions WHERE family_id=$1 AND category=$2
`

type CountSubscriptionCategoriesParams struct {
	FamilyID int64
	Category string
}

func (q *Queries) CountSubscriptionCategories(ctx context.Context, arg CountSubscriptionCategoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscriptionCategories, arg.FamilyID, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (family_id, wallet_id, name, category, amount_minor, next_date, billing_day, interval_months)
VALUES ($1,$2,$3,$4,$5,$6,EXTRACT(DAY FROM $6::date)::smallint,$7) RETURNING id
`

type CreateSubscriptionParams struct {
	FamilyID       int64
	WalletID       int64
	Name           string
	Category       string
	AmountMinor    int64
	NextDate       pgtype.Date
	IntervalMonths int16
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.FamilyID,
		arg.WalletID,
		arg.Name,
		arg.Category,
		arg.AmountMinor,
		arg.NextDate,
		arg.IntervalMonths,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions WHERE family_id=$1 AND id=$2
`

type DeleteSubscriptionParams struct {
	FamilyID int64
	ID       int64
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, arg.FamilyID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, wallet_id, name, category, amount_minor, next_date, interval_months
FROM subscriptions WHERE family_id=$1 AND id=$2 AND active
`

type GetSubscriptionParams struct {
	FamilyID int64
	ID       int64
}

type GetSubscriptionRow struct {
	ID             int64
	WalletID       int64
	Name           string
	Category       string
	AmountMinor    int64
	NextDate       pgtype.Date
	IntervalMonths int16
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (GetSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.FamilyID, arg.ID)
	var i GetSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Name,
		&i.Category,
		&i.AmountMinor,
		&i.NextDate,
		&i.IntervalMonths,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT s.id, s.name, s.wallet_id, w.name AS wallet_name, w.currency,
       s.category, s.amount_minor, s.next_date, s.interval_months, s.active
FROM subscriptions s JOIN wallets w ON w.id = s.wallet_id
WHERE s.family_id = $1 AND (NOT $2::boolean OR s.active)
ORDER BY s.active DESC, s.next_date, s.name
`

type ListSubscriptionsParams struct {
	FamilyID   int64
	ActiveOnly bool
}

type ListSubscriptionsRow struct {
	ID             int64
	Name           string
	WalletID       int64
	WalletName     string
	Currency       string
	Category       string
	AmountMinor    int64
	NextDate       pgtype.Date
	IntervalMonths int16
	Active         bool
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]ListSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptions, arg.FamilyID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsRow
	for rows.Next() {
		var i ListSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WalletID,
			&i.WalletName,
			&i.Currency,
			&i.Category,
			&i.AmountMinor,
			&i.NextDate,
			&i.IntervalMonths,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSubscriptionCategory = `-- name: RenameSubscriptionCategory :exec
UPDATE subscriptions SET category=$1 WHERE family_id=$2 AND category=$3
`

type RenameSubscriptionCategoryParams struct {
	Category   string
	FamilyID   int64
	Category_2 string
}

func (q *Queries) RenameSubscriptionCategory(ctx context.Context, arg RenameSubscriptionCategoryParams) error {
	_, err := q.db.Exec(ctx, renameSubscriptionCategory, arg.Category, arg.FamilyID, arg.Category_2)
	return err
}

const updateSubscription = `-- name: UpdateSubscription :execrows
UPDATE subscriptions SET wallet_id=$1, name=$2, category=$3, amount_minor=$4,
    next_date=$5, billing_day=EXTRACT(DAY FROM $5::date)::smallint, interval_months=$6, active=$7
WHERE family_id=$8 AND id=$9
`

type UpdateSubscriptionParams struct {
	WalletID       int64
	Name           string
	Category       string
	AmountMinor    int64
	NextDate       pgtype.Date
	IntervalMonths int16
	Active         bool
	FamilyID       int64
	ID             int64
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSubscription,
		arg.WalletID,
		arg.Name,
		arg.Category,
		arg.AmountMinor,
		arg.NextDate,
		arg.IntervalMonths,
		arg.Active,
		arg.FamilyID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
