// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions WHERE id = $1 AND family_id = $2
`

type DeleteTransactionParams struct {
	ID       int64
	FamilyID int64
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTransactionSeries = `-- name: DeleteTransactionSeries :execrows
DELETE FROM transactions WHERE family_id = $1 AND series_id = $2
`

type DeleteTransactionSeriesParams struct {
	FamilyID int64
	SeriesID pgtype.Int8
}

func (q *Queries) DeleteTransactionSeries(ctx context.Context, arg DeleteTransactionSeriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTransactionSeries, arg.FamilyID, arg.SeriesID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTransactions = `-- name: GetTransactions :many
SELECT t.id, t.kind, t.occurred_on,
       COALESCE(t.wallet_id, 0) AS wallet_id, COALESCE(w.name, '') AS wallet_name,
       COALESCE(w.currency, t.currency, '') AS wallet_cur,
       t.amount_minor, COALESCE(t.category, '') AS category,
       COALESCE(t.to_wallet_id, 0) AS to_wallet_id, COALESCE(w2.name, '') AS to_wallet_name,
       COALESCE(w2.currency, '') AS to_wallet_cur,
       COALESCE(t.amount_in_minor, 0) AS amount_in_minor, t.admin_fee_minor,
       COALESCE(t.party_id, 0) AS party_id, COALESCE(p.name, '') AS party_name,
       COALESCE(t.investment_id, 0) AS investment_id,
       COALESCE(iv.name, '') AS investment_name,
       COALESCE(iv.varian, '') AS investment_variant,
       COALESCE(t.qty_e8, 0) AS qty_e8, COALESCE(t.cost_basis_minor, 0) AS cost_basis_minor,
       COALESCE(t.series_id, 0) AS series_id, COALESCE(t.series_seq, 0) AS series_seq,
       COALESCE(t.series_n, 0) AS series_n, COALESCE(t.series_kind, '') AS series_kind,
       t.note, COALESCE(u.name, '') AS created_by, t.created_at, t.is_adjustment
FROM transactions t
LEFT JOIN wallets w ON w.id = t.wallet_id
LEFT JOIN wallets w2 ON w2.id = t.to_wallet_id
LEFT JOIN parties p ON p.id = t.party_id
LEFT JOIN investments iv ON iv.id = t.investment_id
LEFT JOIN users u ON u.id = t.created_by
WHERE t.family_id = $1
  AND ($2::bigint = 0 OR t.id = $2)
  AND ($3::bigint = 0 OR t.party_id = $3)
  AND (cardinality($4::text[]) = 0 OR t.kind = ANY($4::text[]))
  AND ($5::text = '' OR t.category = $5::text)
  AND ($6::date IS NULL OR t.occurred_on >= $6::date)
  AND ($7::date IS NULL OR t.occurred_on < $7::date)
  AND ($8::text = '' OR t.note ILIKE '%' || $8::text || '%'
      OR t.category ILIKE '%' || $8::text || '%'
      OR p.name ILIKE '%' || $8::text || '%'
      OR w.name ILIKE '%' || $8::text || '%'
      OR iv.name ILIKE '%' || $8::text || '%')
  AND ($9::bigint = 0 OR t.wallet_id = $9
       OR t.to_wallet_id = $9)
  AND ($10::bigint = 0 OR t.investment_id = $10)
  AND ($11::date IS NULL
       OR (t.occurred_on, t.id) < ($11::date, $12::bigint))
ORDER BY t.occurred_on DESC, t.id DESC
LIMIT NULLIF($13::integer, 0)
`

type GetTransactionsParams struct {
	FamilyID      int64
	TransactionID int64
	PartyID       int64
	Kinds         []string
	Category      string
	FromDate      pgtype.Date
	ToDate        pgtype.Date
	Search        string
	WalletID      int64
	InvestmentID  int64
	BeforeDate    pgtype.Date
	BeforeID      int64
	LimitCount    int32
}

type GetTransactionsRow struct {
	ID                int64
	Kind              string
	OccurredOn        pgtype.Date
	WalletID          int64
	WalletName        string
	WalletCur         string
	AmountMinor       int64
	Category          string
	ToWalletID        int64
	ToWalletName      string
	ToWalletCur       string
	AmountInMinor     int64
	AdminFeeMinor     int64
	PartyID           int64
	PartyName         string
	InvestmentID      int64
	InvestmentName    string
	InvestmentVariant string
	QtyE8             int64
	CostBasisMinor    int64
	SeriesID          int64
	SeriesSeq         int16
	SeriesN           int16
	SeriesKind        string
	Note              string
	CreatedBy         string
	CreatedAt         pgtype.Timestamptz
	IsAdjustment      bool
}

func (q *Queries) GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]GetTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getTransactions,
		arg.FamilyID,
		arg.TransactionID,
		arg.PartyID,
		arg.Kinds,
		arg.Category,
		arg.FromDate,
		arg.ToDate,
		arg.Search,
		arg.WalletID,
		arg.InvestmentID,
		arg.BeforeDate,
		arg.BeforeID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsRow
	for rows.Next() {
		var i GetTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.OccurredOn,
			&i.WalletID,
			&i.WalletName,
			&i.WalletCur,
			&i.AmountMinor,
			&i.Category,
			&i.ToWalletID,
			&i.ToWalletName,
			&i.ToWalletCur,
			&i.AmountInMinor,
			&i.AdminFeeMinor,
			&i.PartyID,
			&i.PartyName,
			&i.InvestmentID,
			&i.InvestmentName,
			&i.InvestmentVariant,
			&i.QtyE8,
			&i.CostBasisMinor,
			&i.SeriesID,
			&i.SeriesSeq,
			&i.SeriesN,
			&i.SeriesKind,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.IsAdjustment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions
  (family_id, kind, occurred_on, wallet_id, currency, amount_minor, category,
   to_wallet_id, amount_in_minor, admin_fee_minor, party_id,
   investment_id, qty_e8, cost_basis_minor, series_id, series_seq, series_n, series_kind,
   note, created_by, is_adjustment)
VALUES ($1, $2, $3::date,
        NULLIF($4::bigint, 0), NULLIF($5::text, '')::char(3),
        $6, NULLIF($7::text, ''),
        NULLIF($8::bigint, 0), NULLIF($9::bigint, 0),
        $10, NULLIF($11::bigint, 0),
        NULLIF($12::bigint, 0), NULLIF($13::bigint, 0),
        $14::bigint,
        NULLIF($15::bigint, 0), NULLIF($16::smallint, 0),
        NULLIF($17::smallint, 0), NULLIF($18::text, ''),
        $19, $20, $21)
RETURNING id
`

type InsertTransactionParams struct {
	FamilyID       int64
	Kind           string
	OccurredOn     pgtype.Date
	WalletID       int64
	Currency       string
	AmountMinor    int64
	Category       string
	ToWalletID     int64
	AmountInMinor  int64
	AdminFeeMinor  int64
	PartyID        int64
	InvestmentID   int64
	QtyE8          int64
	CostBasisMinor pgtype.Int8
	SeriesID       int64
	SeriesSeq      int16
	SeriesN        int16
	SeriesKind     string
	Note           string
	CreatedBy      pgtype.Int8
	IsAdjustment   bool
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.FamilyID,
		arg.Kind,
		arg.OccurredOn,
		arg.WalletID,
		arg.Currency,
		arg.AmountMinor,
		arg.Category,
		arg.ToWalletID,
		arg.AmountInMinor,
		arg.AdminFeeMinor,
		arg.PartyID,
		arg.InvestmentID,
		arg.QtyE8,
		arg.CostBasisMinor,
		arg.SeriesID,
		arg.SeriesSeq,
		arg.SeriesN,
		arg.SeriesKind,
		arg.Note,
		arg.CreatedBy,
		arg.IsAdjustment,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const nextTransactionSeriesID = `-- name: NextTransactionSeriesID :one
SELECT nextval('tx_series_seq')
`

func (q *Queries) NextTransactionSeriesID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextTransactionSeriesID)
	var nextval int64
	err := row.Scan(&nextval)
	return nextval, err
}

const updateTransaction = `-- name: UpdateTransaction :execrows
UPDATE transactions SET occurred_on = $1::date,
       wallet_id = NULLIF($2::bigint, 0),
       currency = NULLIF($3::text, '')::char(3),
       amount_minor = $4, category = NULLIF($5::text, ''),
       to_wallet_id = NULLIF($6::bigint, 0),
       amount_in_minor = NULLIF($7::bigint, 0),
       admin_fee_minor = $8,
       party_id = NULLIF($9::bigint, 0), note = $10
WHERE id = $11 AND kind = $12 AND family_id = $13
`

type UpdateTransactionParams struct {
	OccurredOn    pgtype.Date
	WalletID      int64
	Currency      string
	AmountMinor   int64
	Category      string
	ToWalletID    int64
	AmountInMinor int64
	AdminFeeMinor int64
	PartyID       int64
	Note          string
	ID            int64
	Kind          string
	FamilyID      int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransaction,
		arg.OccurredOn,
		arg.WalletID,
		arg.Currency,
		arg.AmountMinor,
		arg.Category,
		arg.ToWalletID,
		arg.AmountInMinor,
		arg.AdminFeeMinor,
		arg.PartyID,
		arg.Note,
		arg.ID,
		arg.Kind,
		arg.FamilyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTransactionSeries = `-- name: UpdateTransactionSeries :execrows
UPDATE transactions SET category = NULLIF($1::text, ''), note = $2
WHERE family_id = $3 AND series_id = $4
`

type UpdateTransactionSeriesParams struct {
	Category string
	Note     string
	FamilyID int64
	SeriesID pgtype.Int8
}

func (q *Queries) UpdateTransactionSeries(ctx context.Context, arg UpdateTransactionSeriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransactionSeries,
		arg.Category,
		arg.Note,
		arg.FamilyID,
		arg.SeriesID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
