// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWalletTransactions = `-- name: CountWalletTransactions :one
SELECT count(*) FROM transactions
WHERE family_id = $1 AND (wallet_id = $2 OR to_wallet_id = $2)
`

type CountWalletTransactionsParams struct {
	FamilyID int64
	WalletID pgtype.Int8
}

func (q *Queries) CountWalletTransactions(ctx context.Context, arg CountWalletTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTransactions, arg.FamilyID, arg.WalletID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (family_id, name, type, provider, currency, initial_balance_minor,
                     settlement_day, payment_day, credit_limit_minor)
VALUES ($1, $2, $3, NULLIF($4::text, ''),
        $5, $6,
        NULLIF($7::smallint, 0),
        NULLIF($8::smallint, 0),
        NULLIF($9::bigint, 0))
RETURNING id
`

type CreateWalletParams struct {
	FamilyID            int64
	Name                string
	Type                string
	Provider            string
	Currency            string
	InitialBalanceMinor int64
	SettlementDay       int16
	PaymentDay          int16
	CreditLimitMinor    int64
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (int64, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.FamilyID,
		arg.Name,
		arg.Type,
		arg.Provider,
		arg.Currency,
		arg.InitialBalanceMinor,
		arg.SettlementDay,
		arg.PaymentDay,
		arg.CreditLimitMinor,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteWallet = `-- name: DeleteWallet :execrows
DELETE FROM wallets WHERE id = $1 AND family_id = $2
`

type DeleteWalletParams struct {
	ID       int64
	FamilyID int64
}

func (q *Queries) DeleteWallet(ctx context.Context, arg DeleteWalletParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWallet, arg.ID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWallets = `-- name: GetWallets :many
SELECT w.id, w.name, w.type, COALESCE(w.provider, '') AS provider, w.currency,
       w.initial_balance_minor, COALESCE(w.settlement_day, 0) AS settlement_day,
       COALESCE(w.payment_day, 0) AS payment_day,
       COALESCE(w.credit_limit_minor, 0) AS credit_limit_minor,
       (w.initial_balance_minor
       + COALESCE((SELECT SUM(CASE WHEN t.kind IN ('income', 'debt_in', 'loan_in', 'invest_sell')
                                   THEN t.amount_minor ELSE -t.amount_minor END)
                   FROM transactions t
                   WHERE t.wallet_id = w.id AND t.occurred_on <= $1::date), 0)
       + COALESCE((SELECT SUM(t.amount_in_minor)
                   FROM transactions t
                   WHERE t.to_wallet_id = w.id AND t.occurred_on <= $1::date), 0))::bigint AS balance_minor,
       COALESCE((SELECT SUM(CASE WHEN t.kind IN ('income', 'debt_in', 'loan_in', 'invest_sell')
                                 THEN -t.amount_minor ELSE t.amount_minor END)
                 FROM transactions t
                 WHERE t.wallet_id = w.id AND t.occurred_on > $1::date
                   AND t.series_kind = 'cicil'), 0)::bigint AS cicilan_mendatang_minor
FROM wallets w
WHERE w.family_id = $2
  AND ($3::bigint = 0 OR w.id = $3)
ORDER BY w.type, w.id
`

type GetWalletsParams struct {
	Today    pgtype.Date
	FamilyID int64
	WalletID int64
}

type GetWalletsRow struct {
	ID                    int64
	Name                  string
	Type                  string
	Provider              string
	Currency              string
	InitialBalanceMinor   int64
	SettlementDay         int16
	PaymentDay            int16
	CreditLimitMinor      int64
	BalanceMinor          int64
	CicilanMendatangMinor int64
}

func (q *Queries) GetWallets(ctx context.Context, arg GetWalletsParams) ([]GetWalletsRow, error) {
	rows, err := q.db.Query(ctx, getWallets, arg.Today, arg.FamilyID, arg.WalletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWalletsRow
	for rows.Next() {
		var i GetWalletsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Provider,
			&i.Currency,
			&i.InitialBalanceMinor,
			&i.SettlementDay,
			&i.PaymentDay,
			&i.CreditLimitMinor,
			&i.BalanceMinor,
			&i.CicilanMendatangMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWallet = `-- name: UpdateWallet :execrows
UPDATE wallets SET name = $1, type = $2,
       provider = NULLIF($3::text, ''), currency = $4,
       initial_balance_minor = $5,
       settlement_day = NULLIF($6::smallint, 0),
       payment_day = NULLIF($7::smallint, 0),
       credit_limit_minor = NULLIF($8::bigint, 0)
WHERE id = $9 AND family_id = $10
`

type UpdateWalletParams struct {
	Name                string
	Type                string
	Provider            string
	Currency            string
	InitialBalanceMinor int64
	SettlementDay       int16
	PaymentDay          int16
	CreditLimitMinor    int64
	ID                  int64
	FamilyID            int64
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWallet,
		arg.Name,
		arg.Type,
		arg.Provider,
		arg.Currency,
		arg.InitialBalanceMinor,
		arg.SettlementDay,
		arg.PaymentDay,
		arg.CreditLimitMinor,
		arg.ID,
		arg.FamilyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
